// Auto-generated by `cargo run -- sync`. Do not edit manually.

#[path = "19_async/mod.rs"]
pub mod r#async;

#[path = "07_collections/mod.rs"]
pub mod collections;

#[path = "14_concurrency/mod.rs"]
pub mod concurrency;

#[path = "03_control_flow/mod.rs"]
pub mod control_flow;

#[path = "06_enums/mod.rs"]
pub mod enums;

#[path = "08_error_handling/mod.rs"]
pub mod error_handling;

#[path = "02_functions/mod.rs"]
pub mod functions;

#[path = "09_generics/mod.rs"]
pub mod generics;

#[path = "12_iterators/mod.rs"]
pub mod iterators;

#[path = "11_lifetimes/mod.rs"]
pub mod lifetimes;

#[path = "17_macros/mod.rs"]
pub mod macros;

#[path = "15_modules/mod.rs"]
pub mod modules;

#[path = "04_ownership/mod.rs"]
pub mod ownership;

#[path = "20_projects/mod.rs"]
pub mod projects;

#[path = "13_smart_pointers/mod.rs"]
pub mod smart_pointers;

#[path = "05_structs/mod.rs"]
pub mod structs;

#[path = "16_testing/mod.rs"]
pub mod testing;

#[path = "10_traits/mod.rs"]
pub mod traits;

#[path = "18_unsafe/mod.rs"]
pub mod r#unsafe;

#[path = "01_variables/mod.rs"]
pub mod variables;
