// Auto-generated by `cargo run -- sync`

pub mod enums1;
pub mod enums2;
pub mod enums3;
pub mod enums4;
pub mod enums5;
pub mod enums_quiz;
pub mod if_let1;
pub mod if_let2;
pub mod option1;
pub mod option2;
pub mod option3;
pub mod option4;
pub mod option5;
pub mod option6;
pub mod option7;
pub mod result1;
pub mod result2;
pub mod result3;
pub mod result4;
pub mod result5;
pub mod result6;
pub mod result7;
pub mod while_let1;
