// Auto-generated by `cargo run -- sync`

pub mod arc1;
pub mod arc2;
pub mod box1;
pub mod box2;
pub mod box3;
pub mod cow1;
pub mod rc1;
pub mod rc2;
pub mod rc3;
pub mod refcell1;
pub mod refcell2;
pub mod refcell3;
pub mod smart_pointers1;
pub mod smart_pointers_quiz;
pub mod weak1;
