// Auto-generated by `cargo run -- sync`

pub mod borrowing1;
pub mod borrowing2;
pub mod borrowing3;
pub mod borrowing4;
pub mod borrowing5;
pub mod borrowing6;
pub mod borrowing7;
pub mod borrowing8;
pub mod ownership1;
pub mod ownership2;
pub mod ownership3;
pub mod ownership4;
pub mod ownership5;
pub mod ownership6;
pub mod ownership7;
pub mod ownership8;
pub mod ownership_quiz1;
pub mod ownership_quiz2;
pub mod slices1;
pub mod slices2;
pub mod slices3;
pub mod slices4;
pub mod slices5;
