// Auto-generated by `cargo run -- sync`

pub mod main;
pub mod modules1;
pub mod modules2;
pub mod modules3;
pub mod modules4;
pub mod modules5;
pub mod modules6;
pub mod modules7;
pub mod modules8;
pub mod modules_quiz;
