// Auto-generated by `cargo run -- sync`

pub mod lifetimes1;
pub mod lifetimes2;
pub mod lifetimes3;
pub mod lifetimes4;
pub mod lifetimes5;
pub mod lifetimes6;
pub mod lifetimes7;
pub mod lifetimes8;
pub mod lifetimes9;
pub mod lifetimes_quiz;
