// Auto-generated by `cargo run -- sync`

pub mod methods1;
pub mod methods2;
pub mod methods3;
pub mod methods4;
pub mod methods5;
pub mod methods6;
pub mod structs1;
pub mod structs2;
pub mod structs3;
pub mod structs4;
pub mod structs5;
pub mod structs6;
pub mod structs7;
pub mod structs_quiz;
