// Auto-generated by `cargo run -- sync`

pub mod generics1;
pub mod generics2;
pub mod generics3;
pub mod generics4;
pub mod generics5;
pub mod generics6;
pub mod generics7;
pub mod generics8;
pub mod generics9;
pub mod generics_quiz;
