// Auto-generated by `cargo run -- sync`

pub mod collections1;
pub mod collections_quiz;
pub mod hashmap1;
pub mod hashmap2;
pub mod hashmap3;
pub mod hashmap4;
pub mod hashmap5;
pub mod hashmap6;
pub mod hashmap7;
pub mod string1;
pub mod string2;
pub mod string3;
pub mod string4;
pub mod string5;
pub mod string6;
pub mod string7;
pub mod vec1;
pub mod vec2;
pub mod vec3;
pub mod vec4;
pub mod vec5;
pub mod vec6;
pub mod vec7;
pub mod vec8;
