// Auto-generated by `cargo run -- sync`

pub mod async1;
pub mod async2;
pub mod async3;
pub mod async4;
pub mod async5;
pub mod async6;
pub mod async7;
pub mod async8;
pub mod async9;
pub mod async_quiz;
