// Auto-generated by `cargo run -- sync`

pub mod arrays1;
pub mod arrays2;
pub mod arrays3;
pub mod booleans1;
pub mod booleans2;
pub mod casting1;
pub mod casting2;
pub mod chars1;
pub mod chars2;
pub mod constants1;
pub mod constants2;
pub mod floats1;
pub mod floats2;
pub mod integers1;
pub mod integers2;
pub mod integers3;
pub mod primitive_types_quiz;
pub mod tuples1;
pub mod tuples2;
pub mod tuples3;
pub mod variables1;
pub mod variables2;
pub mod variables3;
pub mod variables4;
pub mod variables5;
