// Auto-generated by `cargo run -- sync`

pub mod closures1;
pub mod closures2;
pub mod closures3;
pub mod closures4;
pub mod closures5;
pub mod closures6;
pub mod closures7;
pub mod closures8;
pub mod iterators1;
pub mod iterators10;
pub mod iterators11;
pub mod iterators2;
pub mod iterators3;
pub mod iterators4;
pub mod iterators5;
pub mod iterators6;
pub mod iterators7;
pub mod iterators8;
pub mod iterators9;
pub mod iterators_quiz;
