// Auto-generated by `cargo run -- sync`

pub mod std_traits1;
pub mod std_traits10;
pub mod std_traits2;
pub mod std_traits3;
pub mod std_traits4;
pub mod std_traits5;
pub mod std_traits6;
pub mod std_traits7;
pub mod std_traits8;
pub mod std_traits9;
pub mod trait_objects1;
pub mod trait_objects2;
pub mod trait_objects3;
pub mod trait_objects4;
pub mod traits1;
pub mod traits2;
pub mod traits3;
pub mod traits4;
pub mod traits5;
pub mod traits6;
pub mod traits7;
pub mod traits8;
pub mod traits_advanced1;
pub mod traits_advanced2;
pub mod traits_quiz;
